name: Rust Quality Pipeline for PRs

on:
  pull_request:
    branches:
      - main

jobs:
  quality:
    uses: harmony-labs/workflow-rust/.github/workflows/quality.yaml@v0.2.1
    with:
      lint: false