name: Rust Quality Pipeline for PRs

on:
  pull_request:
    branches:
      - main

jobs:
  quality:
    uses: harmony-labs/workflow-rust/.github/workflows/quality.yaml@main
    with:
      cargo_test_args: '--verbose'
      lint: true